server: 
  port: 9002
spring: 
  application:  
    name: toptalk-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toptalk_recruit?characterEncoding=UTF8
    username: root
    password: ljj19940228
  jpa: 
    database: MySQL
    show-sql: true
  redis:
      host: 10.0.0.6
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka