server: 
  port: 9008
spring: 
  application:  
    name: toptalk-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toptalk_user?characterEncoding=UTF8
    username: root
    password: ljj19940228
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 10.0.0.6
  rabbitmq:
    host: 10.0.0.6
jwt:
  config:
    key: toptalk
    ttl: 360000 #设置有效时长为1小时;
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka