server:
  port: 9001
spring:
  application:
    name: toptalk_base #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toptalk_base?characterEncoding=utf-8
    username: root
    password: ljj19940228
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true