server: 
  port: 9004
spring: 
  application:  
    name: toptalk_article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toptalk_article?characterEncoding=UTF8
    username: root
    password: ljj19940228
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 10.0.0.7
  data:
    mongodb:
      host: 10.0.0.7
      database: recruitdb