server:
  port: 12000
spring:
  application:
    name: toptalk-manager #指定服务名
  cloud:
    config:
      server:
        git:
          uri:
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://localhost:6868/eureka/
