server:
  port: 9012
spring:
  application:
    name: toptalk-web #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://localhost:6868/eureka/
zuul:
  routes:
    toptalk-gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: toptalk-gathering #指定Eureka注册中心中的服务id
    toptalk-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: toptalk-article #指定Eureka注册中心中的服务id
    toptalk-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: toptalk-base #指定Eureka注册中心中的服务id
    toptalk-friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: toptalk-friend #指定Eureka注册中心中的服务id
    toptalk-qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: toptalk-qa #指定Eureka注册中心中的服务id
    toptalk-recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: toptalk-recruit #指定Eureka注册中心中的服务id
    toptalk-spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: toptalk-spit #指定Eureka注册中心中的服务id
    toptalk-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: toptalk-user #指定Eureka注册中心中的服务id
    toptalk-search: #搜索
      path: /search/**
      serviceId: toptalk-search